const types = {

    SET_USER: '@user/SET_USER',
    UPDATE_USER: '@user/UPDATE_USER',

    SET_USER_REDUCER: '@user/SET_USER_REDUCER',

    USER_UPDATE_REQUEST: '@user/USER_UPDATE_REQUEST',
    USER_UPDATE_SUCCESS: '@user/USER_UPDATE_SUCCESS',
    USER_UPDATE_FAILURE: '@user/USER_UPDATE_FAILURE',

    USER_UPDATE_AVATAR: '@user/USER_UPDATE_AVATAR',

    SIGN_IN_SUCCESS: '@auth/SIGN_IN_SUCCESS',
    SIGN_OUT: '@auth/SIGN_OUT'

}

export default types